--------------------------------------------------------------------------------
-- 적용시스템명 :개발계(ORACLE)
-- 테이블 : 고객기본
-- 테이블ID : TBL_CTRMBRCI01
-- 변경일시 : 2020-08-13 17:20:59
-- 최종변경자 : 정선영/1073685
-- 최종승인자 : 김중순/1073680
--------------------------------------------------------------------------------
CREATE TABLE TBL_CTRMBRCI01
(
	CUST_SUID NUMBER(19) NOT NULL ,
	RGSR_EMNB VARCHAR2(10) NOT NULL ,
	RGST_DTTM DATE NOT NULL ,
	RGST_PRGM_ID VARCHAR2(50) NOT NULL ,
	LAST_CHNR_EMNB VARCHAR2(10) NOT NULL ,
	LAST_CHNG_DTTM DATE NOT NULL ,
	LAST_CHNG_PRGM_ID VARCHAR2(50) NOT NULL ,
	DLTN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	RTPN_CUST_NO VARCHAR2(10) NOT NULL ,
	CUST_ID VARCHAR2(10) ,
	GROU_PRSN_DVSN_CODE VARCHAR2(10) ,
	RTPN_CHNL_DVSN_CODE VARCHAR2(10) ,
	STAC_MNTH VARCHAR2(2) ,
	BSKN_DVSN_CODE VARCHAR2(10) ,
	GROP_DVSN_CODE VARCHAR2(10) ,
	OVCR_LSTG_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	CLBS_DATE DATE ,
	CLBS_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	CLBS_RGST_DATE DATE ,
	PSMT_ACPC_DVSN_CODE VARCHAR2(10) ,
	SMS_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	ELCT_POST_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	NTTK_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	PSMT_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	ELCT_RGPS_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	CUST_INFO_OFER_AGRM_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	RTPN_TRNN_REJT_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	MGIV_RPRT_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	MTRT_GUID_RCVE_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	MTRT_GUID_RGST_DVSN_CODE VARCHAR2(10) 
) 
TABLESPACE TSD_NRP01
;



COMMENT ON TABLE TBL_CTRMBRCI01 IS '고객기본';

COMMENT ON COLUMN TBL_CTRMBRCI01.CUST_SUID IS '고객SUID';
COMMENT ON COLUMN TBL_CTRMBRCI01.RGSR_EMNB IS '등록자사원번호';
COMMENT ON COLUMN TBL_CTRMBRCI01.RGST_DTTM IS '등록일시';
COMMENT ON COLUMN TBL_CTRMBRCI01.RGST_PRGM_ID IS '등록프로그램ID';
COMMENT ON COLUMN TBL_CTRMBRCI01.LAST_CHNR_EMNB IS '최종변경자사원번호';
COMMENT ON COLUMN TBL_CTRMBRCI01.LAST_CHNG_DTTM IS '최종변경일시';
COMMENT ON COLUMN TBL_CTRMBRCI01.LAST_CHNG_PRGM_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN TBL_CTRMBRCI01.DLTN_YN IS '삭제여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.RTPN_CUST_NO IS '퇴직연금고객번호';
COMMENT ON COLUMN TBL_CTRMBRCI01.CUST_ID IS '고객ID';
COMMENT ON COLUMN TBL_CTRMBRCI01.GROU_PRSN_DVSN_CODE IS '단체개인구분코드';
COMMENT ON COLUMN TBL_CTRMBRCI01.RTPN_CHNL_DVSN_CODE IS '퇴직연금채널구분코드';
COMMENT ON COLUMN TBL_CTRMBRCI01.STAC_MNTH IS '결산월';
COMMENT ON COLUMN TBL_CTRMBRCI01.BSKN_DVSN_CODE IS '업종구분코드';
COMMENT ON COLUMN TBL_CTRMBRCI01.GROP_DVSN_CODE IS '그룹구분코드';
COMMENT ON COLUMN TBL_CTRMBRCI01.OVCR_LSTG_YN IS '국외상장여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.CLBS_DATE IS '폐업일자';
COMMENT ON COLUMN TBL_CTRMBRCI01.CLBS_YN IS '폐업여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.CLBS_RGST_DATE IS '폐업등록일자';
COMMENT ON COLUMN TBL_CTRMBRCI01.PSMT_ACPC_DVSN_CODE IS '우편물수령지구분코드';
COMMENT ON COLUMN TBL_CTRMBRCI01.SMS_RCVE_YN IS 'SMS수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.ELCT_POST_RCVE_YN IS '전자우편수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.NTTK_RCVE_YN IS '알림톡수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.PSMT_RCVE_YN IS '우편물수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.ELCT_RGPS_RCVE_YN IS '전자등기수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.CUST_INFO_OFER_AGRM_YN IS '고객정보제공동의여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.RTPN_TRNN_REJT_YN IS '퇴직연금거래거절여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.MGIV_RPRT_RCVE_YN IS '운용보고서수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.MTRT_GUID_RCVE_YN IS '만기안내수신여부';
COMMENT ON COLUMN TBL_CTRMBRCI01.MTRT_GUID_RGST_DVSN_CODE IS '만기안내등록구분코드';



--GRANT SELECT ON TBL_CTRMBRCI01 TO RL_CTR_S;
--GRANT SELECT, INSERT, UPDATE, DELETE ON TBL_CTRMBRCI01 TO RL_CTR_A;


ALTER TABLE TBL_CTRMBRCI01 ADD (
 CONSTRAINT UK_CTRMBRCI01_01
 UNIQUE (RTPN_CUST_NO)
USING INDEX TABLESPACE TSI_NRP01);

CREATE  INDEX IDX_CTRMBRCI01_01 ON TBL_CTRMBRCI01
(CUST_ID) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX UK_CTRMBRCI01_01 ON TBL_CTRMBRCI01
 (RTPN_CUST_NO) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX PK_CTRMBRCI01 ON TBL_CTRMBRCI01
 (CUST_SUID) 
 TABLESPACE TSI_NRP01;



ALTER TABLE TBL_CTRMBRCI01 ADD (
 CONSTRAINT PK_CTRMBRCI01
 PRIMARY KEY (CUST_SUID)
USING INDEX TABLESPACE TSI_NRP01);






--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 적용시스템명 :개발계(ORACLE)
-- 테이블 : 가입자기본
-- 테이블ID : TBL_CTRMBRSI01
-- 변경일시 : 2020-12-03 11:53:42
-- 최종변경자 : 박정석/1073682
-- 최종승인자 : 김중순/1073680
--------------------------------------------------------------------------------
CREATE TABLE TBL_CTRMBRSI01
(
	SBSR_SUID NUMBER(19) NOT NULL ,
	RGSR_EMNB VARCHAR2(10) NOT NULL ,
	RGST_DTTM DATE NOT NULL ,
	RGST_PRGM_ID VARCHAR2(50) NOT NULL ,
	LAST_CHNR_EMNB VARCHAR2(10) NOT NULL ,
	LAST_CHNG_DTTM DATE NOT NULL ,
	LAST_CHNG_PRGM_ID VARCHAR2(50) NOT NULL ,
	DLTN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	SBSR_POLY_NO VARCHAR2(10) NOT NULL ,
	GROU_POLY_NO VARCHAR2(10) NOT NULL ,
	MGIV_MGMT_ORGN_CODE VARCHAR2(4) ,
	MGIV_ORGN_MGMT_NO VARCHAR2(50) ,
	RTPN_CUST_NO VARCHAR2(10) ,
	RTPN_CHNL_DVSN_CODE VARCHAR2(10) ,
	RGST_DATE DATE ,
	CHNG_DTTM DATE ,
	RTPN_SBSR_STTS_CODE VARCHAR2(10) ,
	RTPN_SBSR_STTS_DETL_CODE VARCHAR2(10) ,
	TRMN_DATE DATE ,
	ADDN_SBSR_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	DEPT_NM VARCHAR2(150) ,
	OCKN_DVSN_NM VARCHAR2(150) ,
	CLPS_NM VARCHAR2(150) ,
	CUST_MGMT_NO VARCHAR2(50) ,
	ECST_DVSN_CODE VARCHAR2(10) ,
	DRCR_OTPY_MULT NUMBER(10,5) DEFAULT 0 NOT NULL ,
	RSDL_CNTC_TERM NUMBER(9) DEFAULT 0 NOT NULL ,
	STND_WAGE_AMT NUMBER(24,4) DEFAULT 0 NOT NULL ,
	AVRG_WAGE_AMT NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ESTN_RFDT DATE ,
	RTAL_ESTN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ESTN_STUP_RATO_APLY_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	STUP_RATO_APLY_BEFR_ESTN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ENCM_DATE DATE ,
	RTRM_DATE DATE ,
	JOIN_DATE DATE ,
	MDDL_ETCL_DATE DATE ,
	RFDT DATE ,
	INCP_DATE DATE ,
	STUP_RATO_RFDT DATE ,
	STUP_RATO NUMBER(15,5) DEFAULT 0 NOT NULL ,
	FRST_JOIN_DATE DATE ,
	LAST_MDTM_WTMN_DATE DATE ,
	OTSD_SBSR_MGMT_NO VARCHAR2(50) ,
	APPN_TLGR_TRNM_DATE DATE ,
	SBSR_BNDL_PRCS_TYPE_CODE VARCHAR2(10) ,
	TAXB_AMT NUMBER(35,10) ,
	TAXB_TLGR_TRNM_DATE DATE 
) 
TABLESPACE TSD_NRP01
;



COMMENT ON TABLE TBL_CTRMBRSI01 IS '가입자기본';

COMMENT ON COLUMN TBL_CTRMBRSI01.SBSR_SUID IS '가입자SUID';
COMMENT ON COLUMN TBL_CTRMBRSI01.RGSR_EMNB IS '등록자사원번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.RGST_DTTM IS '등록일시';
COMMENT ON COLUMN TBL_CTRMBRSI01.RGST_PRGM_ID IS '등록프로그램ID';
COMMENT ON COLUMN TBL_CTRMBRSI01.LAST_CHNR_EMNB IS '최종변경자사원번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.LAST_CHNG_DTTM IS '최종변경일시';
COMMENT ON COLUMN TBL_CTRMBRSI01.LAST_CHNG_PRGM_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN TBL_CTRMBRSI01.DLTN_YN IS '삭제여부';
COMMENT ON COLUMN TBL_CTRMBRSI01.SBSR_POLY_NO IS '가입자증권번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.GROU_POLY_NO IS '단체증권번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.MGIV_MGMT_ORGN_CODE IS '운용관리기관코드';
COMMENT ON COLUMN TBL_CTRMBRSI01.MGIV_ORGN_MGMT_NO IS '운용기관관리번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.RTPN_CUST_NO IS '퇴직연금고객번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.RTPN_CHNL_DVSN_CODE IS '퇴직연금채널구분코드';
COMMENT ON COLUMN TBL_CTRMBRSI01.RGST_DATE IS '등록일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.CHNG_DTTM IS '변경일시';
COMMENT ON COLUMN TBL_CTRMBRSI01.RTPN_SBSR_STTS_CODE IS '퇴직연금가입자상태코드';
COMMENT ON COLUMN TBL_CTRMBRSI01.RTPN_SBSR_STTS_DETL_CODE IS '퇴직연금가입자상태상세코드';
COMMENT ON COLUMN TBL_CTRMBRSI01.TRMN_DATE IS '소멸일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.ADDN_SBSR_YN IS '추가가입자여부';
COMMENT ON COLUMN TBL_CTRMBRSI01.DEPT_NM IS '부서명';
COMMENT ON COLUMN TBL_CTRMBRSI01.OCKN_DVSN_NM IS '직종구분명';
COMMENT ON COLUMN TBL_CTRMBRSI01.CLPS_NM IS '직급명';
COMMENT ON COLUMN TBL_CTRMBRSI01.CUST_MGMT_NO IS '고객관리번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.ECST_DVSN_CODE IS '임직원구분코드';
COMMENT ON COLUMN TBL_CTRMBRSI01.DRCR_OTPY_MULT IS '임원지급배수';
COMMENT ON COLUMN TBL_CTRMBRSI01.RSDL_CNTC_TERM IS '잔여계약기간';
COMMENT ON COLUMN TBL_CTRMBRSI01.STND_WAGE_AMT IS '기준임금금액';
COMMENT ON COLUMN TBL_CTRMBRSI01.AVRG_WAGE_AMT IS '평균임금금액';
COMMENT ON COLUMN TBL_CTRMBRSI01.ESTN_RFDT IS '추계액기준일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.RTAL_ESTN IS '퇴직금추계액';
COMMENT ON COLUMN TBL_CTRMBRSI01.ESTN_STUP_RATO_APLY_YN IS '추계액설정비율적용여부';
COMMENT ON COLUMN TBL_CTRMBRSI01.STUP_RATO_APLY_BEFR_ESTN IS '설정비율적용전추계액';
COMMENT ON COLUMN TBL_CTRMBRSI01.ENCM_DATE IS '입사일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.RTRM_DATE IS '퇴직일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.JOIN_DATE IS '가입일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.MDDL_ETCL_DATE IS '중간정산일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.RFDT IS '기준일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.INCP_DATE IS '성립일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.STUP_RATO_RFDT IS '설정비율기준일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.STUP_RATO IS '설정비율';
COMMENT ON COLUMN TBL_CTRMBRSI01.FRST_JOIN_DATE IS '최초가입일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.LAST_MDTM_WTMN_DATE IS '최종중도인출일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.OTSD_SBSR_MGMT_NO IS '대외가입자관리번호';
COMMENT ON COLUMN TBL_CTRMBRSI01.APPN_TLGR_TRNM_DATE IS '청약전문전송일자';
COMMENT ON COLUMN TBL_CTRMBRSI01.SBSR_BNDL_PRCS_TYPE_CODE IS '가입자일괄처리유형코드';
COMMENT ON COLUMN TBL_CTRMBRSI01.TAXB_AMT IS '세금우대금액';
COMMENT ON COLUMN TBL_CTRMBRSI01.TAXB_TLGR_TRNM_DATE IS '세금우대전문전송일자';



--GRANT SELECT ON TBL_CTRMBRSI01 TO RL_CTR_S;
--GRANT SELECT, INSERT, UPDATE, DELETE ON TBL_CTRMBRSI01 TO RL_CTR_A;


ALTER TABLE TBL_CTRMBRSI01 ADD (
 CONSTRAINT UK_CTRMBRSI01_01
 UNIQUE (SBSR_POLY_NO,GROU_POLY_NO)
USING INDEX TABLESPACE TSI_NRP01);

CREATE  INDEX IDX_CTRMBRSI01_01 ON TBL_CTRMBRSI01
(GROU_POLY_NO,CHNG_DTTM) 
 TABLESPACE TSI_NRP01;

CREATE  INDEX IDX_CTRMBRSI01_02 ON TBL_CTRMBRSI01
(RTPN_CUST_NO) 
 TABLESPACE TSI_NRP01;

CREATE  INDEX IDX_CTRMBRSI01_03 ON TBL_CTRMBRSI01
(CHNG_DTTM,SBSR_BNDL_PRCS_TYPE_CODE,GROU_POLY_NO) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX UK_CTRMBRSI01_01 ON TBL_CTRMBRSI01
 (SBSR_POLY_NO,GROU_POLY_NO) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX PK_CTRMBRSI01 ON TBL_CTRMBRSI01
 (SBSR_SUID) 
 TABLESPACE TSI_NRP01;



ALTER TABLE TBL_CTRMBRSI01 ADD (
 CONSTRAINT PK_CTRMBRSI01
 PRIMARY KEY (SBSR_SUID)
USING INDEX TABLESPACE TSI_NRP01);






--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 적용시스템명 :개발계(ORACLE)
-- 테이블 : 계약기본
-- 테이블ID : TBL_CTRCTMCN01
-- 변경일시 : 2020-12-08 16:10:26
-- 최종변경자 : 정선영/1073685
-- 최종승인자 : 김중순/1073680
--------------------------------------------------------------------------------
CREATE TABLE TBL_CTRCTMCN01
(
	CNTC_SUID NUMBER(19) NOT NULL ,
	RGSR_EMNB VARCHAR2(10) NOT NULL ,
	RGST_DTTM DATE NOT NULL ,
	RGST_PRGM_ID VARCHAR2(50) NOT NULL ,
	LAST_CHNR_EMNB VARCHAR2(10) NOT NULL ,
	LAST_CHNG_DTTM DATE NOT NULL ,
	LAST_CHNG_PRGM_ID VARCHAR2(50) NOT NULL ,
	DLTN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	GROU_POLY_NO VARCHAR2(10) NOT NULL ,
	SYST_DVSN_CODE VARCHAR2(10) NOT NULL ,
	CNTC_FORM_DVSN_CODE VARCHAR2(10) NOT NULL ,
	MGIV_MGMT_ORGN_CODE VARCHAR2(4) NOT NULL ,
	CNTC_PRGS_STTS_CODE VARCHAR2(10) NOT NULL ,
	RTPN_CNTC_STTS_CODE VARCHAR2(10) ,
	RTPN_CNTC_STTS_DETL_CODE VARCHAR2(10) ,
	RTPN_CHNL_DVSN_CODE VARCHAR2(10) NOT NULL ,
	ANUT_CNTC_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	CNTC_RGST_DATE DATE ,
	CNTC_INCP_DATE DATE ,
	CNTC_TRMN_DATE DATE ,
	CTDT DATE ,
	TRUT_CTDT DATE ,
	FSTM_PAYM_DATE DATE ,
	ISRN_TRUT_DVSN_CODE VARCHAR2(10) ,
	THCO_ROLE_DVSN_CODE VARCHAR2(10) ,
	PAYM_CYCL_CODE VARCHAR2(10) ,
	CLTN_MTHD_CODE VARCHAR2(10) ,
	SHAN_PAYM_STND_MNTH VARCHAR2(2) ,
	SHAN_PAYM_STND_DAY VARCHAR2(2) ,
	SYST_OPTO_DATE DATE ,
	RGLT_APRV_NO VARCHAR2(100) ,
	RGLT_APRV_DATE DATE ,
	LBRR_RPRS_DVSN_CODE VARCHAR2(10) ,
	LBRR_RPRS_NM VARCHAR2(150) ,
	LBRR_RPRS_BTDT DATE ,
	LBRR_RPRS_GNDR_CODE VARCHAR2(10) ,
	CNTC_TRNS_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	CNTC_TRNS_RESN_CODE VARCHAR2(10) ,
	CNTC_TRNS_ORGN_CODE VARCHAR2(4) ,
	TXTN_DFCG_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	ELCT_APPN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	MGRB_PFRP_PAYM_PSSB_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	DRCR_JOIN_PSSB_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	RTPN_BSMN_LMTT_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	FRST_JOIN_DATE DATE ,
	SHAN_PAYM_GRAC_TERM NUMBER(5) ,
	SHAN_GRAC_DVSN_CODE VARCHAR2(10) ,
	CNTC_CNFM_DOCU_DVSN_CODE VARCHAR2(10) ,
	IRP_JOIN_TRGT_CODE VARCHAR2(10) ,
	RCRT_EMNB VARCHAR2(10) ,
	PRCH_EMNB VARCHAR2(10) ,
	CLTN_EMNB VARCHAR2(10) ,
	ATMT_PROD_LNUP_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	RTPN_CUST_NO VARCHAR2(10) ,
	INTG_GROU_POLY_NO VARCHAR2(10) ,
	MXTP_PRTN_POLY_NO VARCHAR2(10) ,
	STUP_RATO NUMBER(15,5) DEFAULT 0 NOT NULL ,
	FEE_ADUP_POLY_NO VARCHAR2(10) ,
	IMDT_RSCS_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	MGIV_NEW_RGST_DATE DATE ,
	MGIV_ORGN_MGMT_NO VARCHAR2(50) ,
	ANUT_ACTU_GROU_CUST_SUID NUMBER(19) ,
	FEE_RCKN_DATE DATE ,
	FEE_RCKN_APLY_DATE DATE ,
	RTPN_NC_DVSN_CODE VARCHAR2(10) ,
	IRP_APPN_DVSN_CODE VARCHAR2(10) ,
	AFLS_DVSN_CODE VARCHAR2(10) ,
	CUST_MGMT_NO VARCHAR2(50) 
) 
TABLESPACE TSD_NRP01
;



COMMENT ON TABLE TBL_CTRCTMCN01 IS '계약기본';

COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_SUID IS '계약SUID';
COMMENT ON COLUMN TBL_CTRCTMCN01.RGSR_EMNB IS '등록자사원번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.RGST_DTTM IS '등록일시';
COMMENT ON COLUMN TBL_CTRCTMCN01.RGST_PRGM_ID IS '등록프로그램ID';
COMMENT ON COLUMN TBL_CTRCTMCN01.LAST_CHNR_EMNB IS '최종변경자사원번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.LAST_CHNG_DTTM IS '최종변경일시';
COMMENT ON COLUMN TBL_CTRCTMCN01.LAST_CHNG_PRGM_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN TBL_CTRCTMCN01.DLTN_YN IS '삭제여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.GROU_POLY_NO IS '단체증권번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.SYST_DVSN_CODE IS '제도구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_FORM_DVSN_CODE IS '계약형태구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.MGIV_MGMT_ORGN_CODE IS '운용관리기관코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_PRGS_STTS_CODE IS '계약진행상태코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.RTPN_CNTC_STTS_CODE IS '퇴직연금계약상태코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.RTPN_CNTC_STTS_DETL_CODE IS '퇴직연금계약상태상세코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.RTPN_CHNL_DVSN_CODE IS '퇴직연금채널구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.ANUT_CNTC_YN IS '연금계약여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_RGST_DATE IS '계약등록일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_INCP_DATE IS '계약성립일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_TRMN_DATE IS '계약소멸일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.CTDT IS '계약일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.TRUT_CTDT IS '신탁계약일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.FSTM_PAYM_DATE IS '초회납입일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.ISRN_TRUT_DVSN_CODE IS '보험신탁구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.THCO_ROLE_DVSN_CODE IS '당사역할구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.PAYM_CYCL_CODE IS '납입주기코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CLTN_MTHD_CODE IS '수금방법코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.SHAN_PAYM_STND_MNTH IS '부담금납입기준월';
COMMENT ON COLUMN TBL_CTRCTMCN01.SHAN_PAYM_STND_DAY IS '부담금납입기준일';
COMMENT ON COLUMN TBL_CTRCTMCN01.SYST_OPTO_DATE IS '제도시행일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.RGLT_APRV_NO IS '규약승인번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.RGLT_APRV_DATE IS '규약승인일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.LBRR_RPRS_DVSN_CODE IS '근로자대표구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.LBRR_RPRS_NM IS '근로자대표명';
COMMENT ON COLUMN TBL_CTRCTMCN01.LBRR_RPRS_BTDT IS '근로자대표생년월일';
COMMENT ON COLUMN TBL_CTRCTMCN01.LBRR_RPRS_GNDR_CODE IS '근로자대표성별코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_TRNS_YN IS '계약이전여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_TRNS_RESN_CODE IS '계약이전사유코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_TRNS_ORGN_CODE IS '계약이전기관코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.TXTN_DFCG_YN IS '과세이연여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.ELCT_APPN_YN IS '전자청약여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.MGRB_PFRP_PAYM_PSSB_YN IS '경영성과급납입가능여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.DRCR_JOIN_PSSB_YN IS '임원가입가능여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.RTPN_BSMN_LMTT_YN IS '퇴직연금사업자한정여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.FRST_JOIN_DATE IS '최초가입일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.SHAN_PAYM_GRAC_TERM IS '부담금납입유예기간';
COMMENT ON COLUMN TBL_CTRCTMCN01.SHAN_GRAC_DVSN_CODE IS '부담금유예구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CNTC_CNFM_DOCU_DVSN_CODE IS '계약확인서류구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.IRP_JOIN_TRGT_CODE IS 'IRP가입대상코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.RCRT_EMNB IS '모집사원번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.PRCH_EMNB IS '담당자사원번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.CLTN_EMNB IS '수금사원번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.ATMT_PROD_LNUP_YN IS '자동상품라인업여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.RTPN_CUST_NO IS '퇴직연금고객번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.INTG_GROU_POLY_NO IS '통합단체증권번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.MXTP_PRTN_POLY_NO IS '혼합형상대증권번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.STUP_RATO IS '설정비율';
COMMENT ON COLUMN TBL_CTRCTMCN01.FEE_ADUP_POLY_NO IS '수수료합산증권번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.IMDT_RSCS_YN IS '즉시해지여부';
COMMENT ON COLUMN TBL_CTRCTMCN01.MGIV_NEW_RGST_DATE IS '운용신규등록일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.MGIV_ORGN_MGMT_NO IS '운용기관관리번호';
COMMENT ON COLUMN TBL_CTRCTMCN01.ANUT_ACTU_GROU_CUST_SUID IS '연금계리단체고객SUID';
COMMENT ON COLUMN TBL_CTRCTMCN01.FEE_RCKN_DATE IS '수수료기산일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.FEE_RCKN_APLY_DATE IS '수수료기산적용일자';
COMMENT ON COLUMN TBL_CTRCTMCN01.RTPN_NC_DVSN_CODE IS '퇴직연금신계약구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.IRP_APPN_DVSN_CODE IS 'IRP청약구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.AFLS_DVSN_CODE IS '계열사구분코드';
COMMENT ON COLUMN TBL_CTRCTMCN01.CUST_MGMT_NO IS '고객관리번호';



--GRANT SELECT ON TBL_CTRCTMCN01 TO RL_CTR_S;
--GRANT SELECT, INSERT, UPDATE, DELETE ON TBL_CTRCTMCN01 TO RL_CTR_A;


ALTER TABLE TBL_CTRCTMCN01 ADD (
 CONSTRAINT UK_CTRCTMCN01_01
 UNIQUE (GROU_POLY_NO)
USING INDEX TABLESPACE TSI_NRP01);

CREATE  INDEX IDX_CTRCTMCN01_01 ON TBL_CTRCTMCN01
(ANUT_ACTU_GROU_CUST_SUID) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX UK_CTRCTMCN01_01 ON TBL_CTRCTMCN01
 (GROU_POLY_NO) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX PK_CTRCTMCN01 ON TBL_CTRCTMCN01
 (CNTC_SUID) 
 TABLESPACE TSI_NRP01;



ALTER TABLE TBL_CTRCTMCN01 ADD (
 CONSTRAINT PK_CTRCTMCN01
 PRIMARY KEY (CNTC_SUID)
USING INDEX TABLESPACE TSI_NRP01);






--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 적용시스템명 :개발계(ORACLE)
-- 테이블 : 부담금기본
-- 테이블ID : TBL_CTRCTBSA01
-- 변경일시 : 2020-12-22 14:29:36
-- 최종변경자 : 박정석/1073682
-- 최종승인자 : 김중순/1073680
--------------------------------------------------------------------------------
CREATE TABLE TBL_CTRCTBSA01
(
	INTG_TRNN_SUID NUMBER(19) NOT NULL ,
	RGSR_EMNB VARCHAR2(10) NOT NULL ,
	RGST_DTTM DATE NOT NULL ,
	RGST_PRGM_ID VARCHAR2(50) NOT NULL ,
	LAST_CHNR_EMNB VARCHAR2(10) NOT NULL ,
	LAST_CHNG_DTTM DATE NOT NULL ,
	LAST_CHNG_PRGM_ID VARCHAR2(50) NOT NULL ,
	DLTN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	GROU_POLY_NO VARCHAR2(10) NOT NULL ,
	SYST_DVSN_CODE VARCHAR2(10) NOT NULL ,
	ASET_MGMT_ORGN_CODE VARCHAR2(4) NOT NULL ,
	PAYM_TMTH NUMBER(5) DEFAULT 0 NOT NULL ,
	DPST_PLND_DATE DATE ,
	SHAN_BSWR_DVSN_CODE VARCHAR2(10) ,
	PAYM_DATE DATE ,
	SHAN_PAYM_STTS_CODE VARCHAR2(10) NOT NULL ,
	SHAN_SUM_AMT NUMBER(24,4) DEFAULT 0 NOT NULL ,
	USER_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SBSR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	STDD_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SPMT_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	MGRB_OUCM_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	STOF_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SPCL_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	DELY_INRS NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ISA_ACNT_TRNS_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ISDC_ACLT_TRNS_AMT NUMBER(24,4) DEFAULT 0 NOT NULL ,
	USER_TMPN_CNVR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SBSR_TMPN_CNVR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	OTHR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	DPST_PRCS_DTTM DATE ,
	DPST_PRCS_EMNB VARCHAR2(10) ,
	DPST_CNPR_DTTM DATE ,
	DPST_CNPR_EMNB VARCHAR2(10) ,
	DPST_TLGR_MGMT_NO VARCHAR2(20) ,
	CNCL_ORGL_TLGR_MGMT_NO VARCHAR2(20) ,
	CLTN_EMNB VARCHAR2(10) ,
	AENT_BELN_TEAM_CODE VARCHAR2(10) ,
	CLTN_EMPE_BELN_ORGN_CODE VARCHAR2(5) ,
	RTPN_CHNL_DVSN_CODE VARCHAR2(10) NOT NULL ,
	TLGR_TRAS_DTTM DATE ,
	TLGR_RCVE_DTTM DATE ,
	SHAN_ATCM_FILE_MGMT_NO VARCHAR2(50) ,
	SBSR_REGT_BNDL_PRCS_SUID NUMBER(19) 
) 
TABLESPACE TSD_NRP01
;



COMMENT ON TABLE TBL_CTRCTBSA01 IS '부담금기본';

COMMENT ON COLUMN TBL_CTRCTBSA01.INTG_TRNN_SUID IS '통합거래SUID';
COMMENT ON COLUMN TBL_CTRCTBSA01.RGSR_EMNB IS '등록자사원번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.RGST_DTTM IS '등록일시';
COMMENT ON COLUMN TBL_CTRCTBSA01.RGST_PRGM_ID IS '등록프로그램ID';
COMMENT ON COLUMN TBL_CTRCTBSA01.LAST_CHNR_EMNB IS '최종변경자사원번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.LAST_CHNG_DTTM IS '최종변경일시';
COMMENT ON COLUMN TBL_CTRCTBSA01.LAST_CHNG_PRGM_ID IS '최종변경프로그램ID';
COMMENT ON COLUMN TBL_CTRCTBSA01.DLTN_YN IS '삭제여부';
COMMENT ON COLUMN TBL_CTRCTBSA01.GROU_POLY_NO IS '단체증권번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.SYST_DVSN_CODE IS '제도구분코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.ASET_MGMT_ORGN_CODE IS '자산관리기관코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.PAYM_TMTH IS '납입회차';
COMMENT ON COLUMN TBL_CTRCTBSA01.DPST_PLND_DATE IS '입금예정일자';
COMMENT ON COLUMN TBL_CTRCTBSA01.SHAN_BSWR_DVSN_CODE IS '부담금업무구분코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.PAYM_DATE IS '납입일자';
COMMENT ON COLUMN TBL_CTRCTBSA01.SHAN_PAYM_STTS_CODE IS '부담금납입상태코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.SHAN_SUM_AMT IS '부담금합계금액';
COMMENT ON COLUMN TBL_CTRCTBSA01.USER_SHAN IS '사용자부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.SBSR_SHAN IS '가입자부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.STDD_SHAN IS '표준부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.SPMT_SHAN IS '보충부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.MGRB_OUCM_SHAN IS '경영성과부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.STOF_SHAN IS '상계부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.SPCL_SHAN IS '특별부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.DELY_INRS IS '지연이자';
COMMENT ON COLUMN TBL_CTRCTBSA01.ISA_ACNT_TRNS_SHAN IS 'ISA계좌이전부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.ISDC_ACLT_TRNS_AMT IS '사내적립이전금액';
COMMENT ON COLUMN TBL_CTRCTBSA01.USER_TMPN_CNVR_SHAN IS '사용자일시전환부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.SBSR_TMPN_CNVR_SHAN IS '가입자일시전환부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.OTHR_SHAN IS '기타부담금';
COMMENT ON COLUMN TBL_CTRCTBSA01.DPST_PRCS_DTTM IS '입금처리일시';
COMMENT ON COLUMN TBL_CTRCTBSA01.DPST_PRCS_EMNB IS '입금처리사원번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.DPST_CNPR_DTTM IS '입금취소처리일시';
COMMENT ON COLUMN TBL_CTRCTBSA01.DPST_CNPR_EMNB IS '입금취소처리사원번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.DPST_TLGR_MGMT_NO IS '입금전문관리번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.CNCL_ORGL_TLGR_MGMT_NO IS '취소원전문관리번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.CLTN_EMNB IS '수금사원번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.AENT_BELN_TEAM_CODE IS '수금인소속팀코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.CLTN_EMPE_BELN_ORGN_CODE IS '수금사원소속기관코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.RTPN_CHNL_DVSN_CODE IS '퇴직연금채널구분코드';
COMMENT ON COLUMN TBL_CTRCTBSA01.TLGR_TRAS_DTTM IS '전문송신일시';
COMMENT ON COLUMN TBL_CTRCTBSA01.TLGR_RCVE_DTTM IS '전문수신일시';
COMMENT ON COLUMN TBL_CTRCTBSA01.SHAN_ATCM_FILE_MGMT_NO IS '부담금첨부파일관리번호';
COMMENT ON COLUMN TBL_CTRCTBSA01.SBSR_REGT_BNDL_PRCS_SUID IS '가입자명부일괄처리SUID';



--GRANT SELECT ON TBL_CTRCTBSA01 TO RL_CTR_S;
--GRANT SELECT, INSERT, UPDATE, DELETE ON TBL_CTRCTBSA01 TO RL_CTR_A;


ALTER TABLE TBL_CTRCTBSA01 ADD (
 CONSTRAINT UK_CTRCTBSA01_01
 UNIQUE (GROU_POLY_NO,ASET_MGMT_ORGN_CODE,PAYM_TMTH)
USING INDEX TABLESPACE TSI_NRP01);

CREATE  INDEX IDX_CTRCTBSA01_01 ON TBL_CTRCTBSA01
(DPST_PLND_DATE) 
 TABLESPACE TSI_NRP01;

CREATE  INDEX IDX_CTRCTBSA01_02 ON TBL_CTRCTBSA01
(PAYM_DATE) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX UK_CTRCTBSA01_01 ON TBL_CTRCTBSA01
 (GROU_POLY_NO,ASET_MGMT_ORGN_CODE,PAYM_TMTH) 
 TABLESPACE TSI_NRP01;

CREATE UNIQUE INDEX PK_CTRCTBSA01 ON TBL_CTRCTBSA01
 (INTG_TRNN_SUID) 
 TABLESPACE TSI_NRP01;



ALTER TABLE TBL_CTRCTBSA01 ADD (
 CONSTRAINT PK_CTRCTBSA01
 PRIMARY KEY (INTG_TRNN_SUID)
USING INDEX TABLESPACE TSI_NRP01);






--------------------------------------------------------------------------------


