var sql = `CREATE TABLE TBL_CTRCTBSA01
(
	INTG_TRNN_SUID NUMBER(19) NOT NULL ,
	RGSR_EMNB VARCHAR2(10) NOT NULL ,
	RGST_DTTM DATE NOT NULL ,
	RGST_PRGM_ID VARCHAR2(50) NOT NULL ,
	LAST_CHNR_EMNB VARCHAR2(10) NOT NULL ,
	LAST_CHNG_DTTM DATE NOT NULL ,
	LAST_CHNG_PRGM_ID VARCHAR2(50) NOT NULL ,
	DLTN_YN VARCHAR2(1) DEFAULT 'N' NOT NULL ,
	GROU_POLY_NO VARCHAR2(10) NOT NULL ,
	SYST_DVSN_CODE VARCHAR2(10) NOT NULL ,
	ASET_MGMT_ORGN_CODE VARCHAR2(4) NOT NULL ,
	PAYM_TMTH NUMBER(5) DEFAULT 0 NOT NULL ,
	DPST_PLND_DATE DATE ,
	SHAN_BSWR_DVSN_CODE VARCHAR2(10) ,
	PAYM_DATE DATE ,
	SHAN_PAYM_STTS_CODE VARCHAR2(10) NOT NULL ,
	SHAN_SUM_AMT NUMBER(24,4) DEFAULT 0 NOT NULL ,
	USER_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SBSR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	STDD_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SPMT_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	MGRB_OUCM_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	STOF_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SPCL_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	DELY_INRS NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ISA_ACNT_TRNS_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	ISDC_ACLT_TRNS_AMT NUMBER(24,4) DEFAULT 0 NOT NULL ,
	USER_TMPN_CNVR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	SBSR_TMPN_CNVR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	OTHR_SHAN NUMBER(24,4) DEFAULT 0 NOT NULL ,
	DPST_PRCS_DTTM DATE ,
	DPST_PRCS_EMNB VARCHAR2(10) ,
	DPST_CNPR_DTTM DATE ,
	DPST_CNPR_EMNB VARCHAR2(10) ,
	DPST_TLGR_MGMT_NO VARCHAR2(20) ,
	CNCL_ORGL_TLGR_MGMT_NO VARCHAR2(20) ,
	CLTN_EMNB VARCHAR2(10) ,
	AENT_BELN_TEAM_CODE VARCHAR2(10) ,
	CLTN_EMPE_BELN_ORGN_CODE VARCHAR2(5) ,
	RTPN_CHNL_DVSN_CODE VARCHAR2(10) NOT NULL ,
	TLGR_TRAS_DTTM DATE ,
	TLGR_RCVE_DTTM DATE ,
	SHAN_ATCM_FILE_MGMT_NO VARCHAR2(50) ,
	SBSR_REGT_BNDL_PRCS_SUID NUMBER(19) 
) 
;`;
var parse = require("node-sqlparser").parse;
var stringify = require("node-sqlparser").stringify;
var astObj = parse(sql);

var sqlstr = stringify(astObj);
console.log(astObj);
